### ISSUE TITLE
Is there any expected deadline to opensource realm-sync?

### ISSUE THREAD

**Issue by xyklex** [realm/realm-object-store#1062]
I'm working in adding a realm app on a ARM platform (Raspberry Pi for now but I'll soon have others SBC) and I'm using Yocto to generate the OS, and I'll like to get realm components compiled.

This is what I understand until now about the components architecture (if this is not correct I'll be more than happy to get the correct information):

`realm-js -> realm-object-store -> realm-core / realm-sync`

So I was able to compile `realm-core` in Raspberry Pi, because I found a commit related to RPi support.

I tried after with `realm-object-store` but here I found it can use an already compiled `realm-core` or it will download and build it. But when it comes to `realm-sync` it uses a private repository, I found a comment in a Jenkinsfile saying that `realm-sync` could be in future opensourced. 

I would like to know if this is something already in plans or if not how can I get `realm-object-store` compiled for ARM and with Sync support, my goal is to deploy Javascript apps that makes use of Realm.

Thanks in advance.

**Comment by ironage** [comment]
We do plan on open sourcing the sync client code. The way we plan to do this is by merging the sync code into realm-core so that we have a simpler unified build system. You can see the early stages of this migration already in a branch [here.](https://github.com/realm/realm-core/tree/monorepo/src/realm/sync). While this migration is currently in progress, I can't say when it will be finished because it requires changes downstream to consume the new structure.

Related to building js on raspberry pi, we have recently added support for that (https://github.com/realm/realm-js/pull/2912). Is this sufficient for you? It doesn't need to have access to realm-sync because sync now publishes an arm library.

**Comment by xyklex** [comment]
@ironage thanks, that's what I wanted, I'm going to give it a try and let you know.
