### ISSUE TITLE
Update primary key implementation to use `SetUnique` instruction

### ISSUE THREAD

**Issue by jpsim** [realm/realm-object-store#138]
See realm/realm-core#2026, realm/realm-object-store-private#12 and realm/realm-object-store#137 for existing related work on this.

There's a companion issue to do this on the cocoa side here: realm/realm-cocoa#3998

**Comment by jpsim** [comment]
Done in #4003.

**Comment by bdash** [comment]
This was done for Cocoa in realm/realm-cocoa#4003, but it still remains to be done in object store.

**Comment by jpsim** [comment]
Ok, sorry about that & thanks for reopening.

**Comment by simonask** [comment]
Just a reminder: The updates to the PK metadata table also need to be using `set_string_unique` etc., if this doesn't already happen (I don't remember seeing a PR introducing it, but I could have missed it).

Otherwise, duplicate entries will end up in the PK metadata table, which is probably benign as long as all clients actually agree on which column to use as the primary key and so on, but it could cause some serious hard to detect weirdness if they don't.

Again, sorry if this has already been implemented. :-)

**Comment by bdash** [comment]
This was fixed by #162 and #168.
