### ISSUE TITLE
startup troubles on a letsencrypt host

### ISSUE THREAD

**Issue by kristofer** [realm/realm-object-store#190]
so is there anyway to register a new admin user other than http://127.0.0.1:27080 ??
what do I do if it's headless server on digital ocean?

**Comment by kristofer** [comment]
so I had to create an ssh tunnel
ssh -L 9000:127.0.0.1:27080 foo@thedomainImusing.com

and the locally open localhost:9000

**Comment by bdash** [comment]
@kristofer, this current repository relates to an implementation detail of the Realm Mobile Database. For questions about the Realm Mobile Platform please either email help@realm.io, or file issues against https://github.com/realm/realm-mobile-platform.

One way to address your problem is to alter the server's configuration.yml to have it listen on all interfaces, then open up the appropriate ports in your machine's firewall. If you need any further assistance with this, please reach out via one of the two routes mentioned above so someone on the Mobile Platform team can help you.

**Comment by kristofer** [comment]
righty-o, Thanks!
