### ISSUE TITLE
Reevaluate the restriction that a given user can only have the same synced URL open once

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#243]
`SyncUser::register_session` currently enforces a restriction that a given user can only have the same synced URL open once. There are plausible use cases where a user would have the same synced URL open at multiple, different local paths. I'm not aware of a reason for the restriction to exist.

@mrackwitz is running into this restriction in realm/realm-js#679, which was masked by the deadlock fixed in #242.

/cc @austinzheng

**Comment by austinzheng** [comment]
The most straightforward way to fix this is to have `SyncUser` store sessions based on their local path, not on their URL. We may or may not be able to replace `SyncUser`'s map member variables with calls to `SyncManager`, since `SyncManager` also stores sessions based on local path. We can then leave it up to the bindings if they want to provide a feature to map URLs to sessions.

**Comment by austinzheng** [comment]
@mrackwitz, is this ticket blocking client permissions?

**Comment by mrackwitz** [comment]
Not directly, it is only breaking the integration test on realm-sync-services (& realm-js). For now we can probably just disable this test.
