### ISSUE TITLE
Basic Cascading Deletes Implementation

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-object-store#492]
Copying over from https://github.com/realm/realm-core/issues/2718 since this could be done at the Object Store level as well:

>Given that we now have support to get the [total backlinks on a given object](https://github.com/realm/realm-core/pull/2672), this opens up the ability to do a basic implementation of cascading deletes. While this will not be a complete solution, and leaves the potential for orphans when using synchronized Realms, we should not use this as an excuse to ignore. Cascading deletes is one of the most requested features by users of all our SDKs, even a small win for some of these users would go a long way.
>
>At it's most simplest, we could offer a method: `delete(object: anObject, cascade: true)` where the logic will traverse the links from this parent to leaf objects, then check if [`get_backlink_count() == 0`](https://github.com/realm/realm-core/blob/ac284be33d57b46caf6a8c8757050978a4202881/src/realm/row.hpp#L132) to decide if that object should be deleted. The logic will continue back up the tree until it reaches the parent object, and finally deleting it.
>
>Additional improvements could be added to make this more powerful, including:
>* weak/strong link definition in the schema to provide more granularity in the data model
>* provide additional semantics that ensure more predictable results with synchronization
>
>But again, these limitations don't seem to be enough to hold a basic implementation that would definitely suffice for apps using document-based data models or similar. cc @astigsen

**Comment by tgoyne** [comment]
Why would we want to build new cascading delete functionality in the object store rather than just exposing core's existing functionality? The only reason we didn't ship it years ago is we didn't want to commit to semantics we weren't sure we could make work sensibly with sync.

**Comment by bigfish24** [comment]
@tgoyne I had no idea core contained such functionality!? This is exciting news then...

**Comment by bigfish24** [comment]
Aha, I see these notes in the [table header file](https://github.com/realm/realm-core/blob/ad80c3bb04f63e9f94f5242d05114b1642c9563d/src/realm/table.hpp#L1234). Could someone explain how this would work at API level for SDKs?

**Comment by bmunkholm** [comment]
@tgoyne @bdash Any thoughts on above?

**Comment by tgoyne** [comment]
Reference-count based cascading deletes fundamentally doesn't work in a distributed system with no single source of truth without the ability to undelete objects, which we currently don't have. The problem is not that it will leave orphans, but rather that objects which are still referenced by live objects will get deleted. The two potential solutions that I recall being brought up at previous Realmstravaganzas are:

1. Figure out some way to make it possible to "resurrected" deleted objects which doesn't result in the server's disk usage inherently growing indefinitely.
2. Only support strong ownership semantics, where deleting an object deletes all objects it links to even if they're referenced by other objects.

**Comment by bigfish24** [comment]
@tgoyne thanks for the info. This does help clarify, but I am wondering if we are overthinking the problem at least from a real-world need scenario. Today with sync if I wanted to manually build a cascading delete system around Realm (which I assume developers do.. I personally did it with Roobiq), it would have these same limitations, because deletes always win (please correct me if I am wrong).

So the way I am thinking about it is that when people complain about not having cascading deletes, they are not complaining about this issue that we foresee with our sync system, but rather they just don't want to spend the time building their own functionality.

My recommendation is that we should just ignore this limitation and ship the cascading delete functionality if we already have it built. First, the vast majority of our users and our developer credibility comes from the database, so this would still be a huge win for them and keep Realm as a leading client database compared to SQLite/CoreData.

Secondly, we can document this limitation and if developers complain that they need a solution that fully works with sync, we can pursue the "resurrect" strategy (alternatively I could imagine, developers might prefer we establish a source of truth in the server, where the client APIs are async and only available online... something you could build through functions if we offered cascading deletes such that the server only performs it).

**Comment by tgoyne** [comment]
The advantage of people writing their own cascading delete functions is that when they do run into problems with the code they wrote, they do not write blog posts about how Realm is broken garbage and tell people about their horrible experience with it. Some of them will even think through the implications of the code they have written and make sure that their app handles it. Features which appear to work when you're testing it in simple scenarios and then break in very weird ways in production can be much worse than not having the feature at all.

 > we can pursue the "resurrect" strategy

Do you understand that we do not currently have any viable ideas for how do to that, and not because we have not thought about it?

**Comment by bigfish24** [comment]
Your language of "broken garbage" seems either to be dramatic or I do misunderstand the limitations.

>Do you understand that we do not currently have any viable ideas for how do to that, and not because we have not thought about it?

Yes, we can leave it for another day.

I don't think the risk of blog posts is worth preventing us from making out RMD users happy. This is such a highly requested feature that we could trigger blog posts praising us, negating any potential for bad posts at some later point (which likely isn't a big deal if we really highlight the limitation in our docs).

**Comment by bigfish24** [comment]
Assuming https://github.com/realm/realm-core/issues/2718 has or will be released, are we moving forward with this?

**Comment by cmelchior** [comment]
With Partial Sync and Array of Primitives, I doubt we have time to implement this.

Also, note that the standard `ON DELETE CASCADE` in SQLite delete child objects no matter how many objects reference them. Adopting that definition for an initial version of this would avoid a lot of the pitfalls mentioned above.

**Comment by bigfish24** [comment]
👍 I am fine with leaving out of 2.0, not a headliner if that's consensus.

**Comment by roberhofer** [comment]
Referenced in AHA here: https://realmio.aha.io/features/PROD-13
