### ISSUE TITLE
Ambiguous behaviour of logout can cause lost of unsynchronised data

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#518]
Can you please clarify/confirm the behavior described in this section https://realm.io/docs/objc/latest/#logging-out
especially this part

>  Any pending local changes will continue to be uploaded until the Realm Object Server has been fully synchronized

When the user logout, the OS call `session->log_out()`, if the session is in `Active`, `WaitingForAccessToken` or `Dying` state, this will move the session's state to `Inactive` (in the hope that another login will revive the session ...)
https://github.com/realm/realm-object-store/blob/fd7eabba5f33a90fb58c45e78415c1202cd2333b/src/sync/sync_user.cpp#L163-L165

Currently, entering the `Inactive` state will not wait for the upload to complete, as I may infer from the doc, this actually will happen only when closing the Realm (and associated sessions)
as `session->close` will allow the session to enter the `Dying` state which will allow the upload to complete (if the _StopPolicy_ is `AfterChangesUploaded`) https://github.com/realm/realm-object-store/blob/fd7eabba5f33a90fb58c45e78415c1202cd2333b/src/sync/sync_session.cpp#L282

**Q1**: 

Am I missing something or misunderstanding the doc/code?

_(summary)_

- if you close the Realm (or goes out of scope) (without logout) you go from `Active` -> `Dying` (upload will happen)
- if you `logout` you go from `Active` -> `Inactive` (no upload)
- if you `logout` from `WaitingForAccessToken`|| `Dying` -> `Inactive` (no upload)
 (other state `logout` is a no-op)

**Q2**: 

Giving that the session can be in another state than `Active` when we call `close`, there’s no
guarantee that an `access_token` will be fetched which will allow the upload to complete, this similar use case is highlighted in this _FIXME_ https://github.com/realm/realm-object-store/blob/fd7eabba5f33a90fb58c45e78415c1202cd2333b/src/sync/sync_session.cpp#L319
As a consequence, it will be dangerous to remove the Realm on the next app startup, because the user may lose unsynchronized changes

cc @austinzheng

**Comment by austinzheng** [comment]
I think the docstring needs to be changed, and the behavior is intentional.

1. There's no guarantee that the user will remain online long enough to upload pending changes, or that the device will ever be online in the future long enough to upload changes (especially across application launches), which means the actual process of logging out can be delayed indefinitely. We deemed that having some certainty with regards to when a user's Realms are locally deleted (e.g. for sure upon next application launch) is more important.

2. The app developer has the tools in the API to manually ensure that logging out never occurs while pending change exist. If we went to the "wait for changes to upload" behavior, they have no tools to ensure the Realm files are deleted for sure.

We can revisit this, but we probably need an actual design document/desired semantics this time around. Multiple modes could be a thing.
