### ISSUE TITLE
Object::create writes redundant information

### ISSUE THREAD

**Issue by ironage** [realm/realm-object-store#661]
There’s a method in object store [`Object::create`](https://github.com/realm/realm-object-store/blob/master/src/object_accessor.hpp#L171) which has a `update` parameter. If the object exists already (as given by the primary key property), then the method will iterate through all properties and set them again, even if they are in fact the same and no update is needed. As a consumer of the js binding for the loader, I expected that I could pass in a fully populated object and only the properties which have changed would be updated. This is not the case since I see that all properties are set. The loader works in two stages, populate the objects, then fill in the links with the previously generated object ids. Since we used the create method which set everything, we were essentially creating much larger data in the history of the client than necessary. In my local test of 500000 rows, when I changed away from using `create` and made a regular object assignment for only the properties that changed on the second pass (the links if they were not null) I saw a significant improvement in speed and memory useage:

|  | `Object::create(...update=true)` | Update properties manually |
|--|---------------------------------|----------------------------|
| Size of client Realm file |  384M  | 288M   | 
| Maximum resident set size | 1.67GB  |  1.32GB |
| Load time (real) | 49.75s  | 37.09  |

I assume the extra memory used is because of the sync transaction log since at the core level, no COW is performed when the values are identical. Can we change `Object::create` to only update properties that have not changed, or is this important for sync purposes?

**Comment by tgoyne** [comment]
Older discussion related to this: https://github.com/realm/realm-core/issues/2787

**Comment by nirinchev** [comment]
@ironage we had a similar issue with the GraphQL service where I implemented a diffing update mechanism. Since it's in js, perhaps you can just copy-paste it with minimal adjustments for the loader purposes.

**Comment by simonask** [comment]
To summarize the discussion in realm/realm-core#2787, it has to do with the timestamps recorded by Sync whenever a change is made. If a client is offline for a long time, skipping an update because the value in the database happens to be identical to the incoming value creates slightly different behavior (i.e. the value may fail to revert an older change on the server).

I believe the best way to address this is actually at-rest log compaction on the client. Right now we only compact the client's log when uploading to the server, but we could just as well do it every N commits (possibly N=1) when we store the changes in the database. Log compaction is able to discard the older `Set` instruction, rather than the latest.

**Comment by ironage** [comment]
Thanks for the clarification. I'll close this issue since it wouldn't involve changing this method in the object store.
