### ISSUE TITLE
Prevent creating classes prefixed by `__`

### ISSUE THREAD

**Issue by kneth** [realm/realm-object-store#704]
In sync we have a number of classes with names prefixed by `__` (`__User`, `__ResultSets`, ...). We should reserved all such class names for the future, and simply prevent users to create such classes.

**Comment by sipersso** [comment]
I am forced to create all these classes in my own local realms. Why? Because I already have a local realm in production and I want to migrate my users. Of course I want to be able to reuse the objects between the local and the synced realms. So my objects have a reference to Permission objects. In the local objects these are empty and in the synced realms they are populated, which forces see to add the "__User" objects etc to the realm migration. 

I assume this will be a very common scenario. To move a local app to realm cloud. Please consider this when enforcing policies on class names. Also, it would probably be good to figure out an easier way to reuse objects between local and synced realms.
