### ISSUE TITLE
Allow developers to change the query of a named subscription after it is active

### ISSUE THREAD

**Issue by ianpward** [realm/realm-object-store#767]
Adding another parameter to subscribe() to let them ask for it to just overwrite the existing one instead wouldn't be hard and would be useful

cc. @roberhofer @astigsen

**Comment by simonask** [comment]
For the record, Sync is fine with all of this. :-)

**Comment by nirinchev** [comment]
@cmelchior why would we need a `setName()`? I believe what Ian wants is something like:

```js
const subscription = realm.objects("Foo").filtered("Bar = 5").subscribe("MainScreenFoos");

const sameSubscription = realm.objects("Foo").filtered("Bar >= 5).subscribe("MainScreenFoos", /* override */ true);
```

**Comment by simonask** [comment]
I don't think it makes a difference from the server's perspective. Assuming the add/remove of a query arrives in the same work unit on the server (which isn't guaranteed, since they happen in separate write transactions, but it is not unlikely), the server will rerun the queries and diff against the current subscription anyway. :-)

**Comment by tgoyne** [comment]
Why do you think it is unlikely that they will arrive separately? A decent amount of stuff happens between when we notify sync about the first write transaction and when we start the second one.

**Comment by astigsen** [comment]
It would be really nice if this could percolate all the way down to the (previous) query itself, so that any UI that observed that query would be updated automatically.

**Comment by astigsen** [comment]
> The API I had in mind for Swift when we talked about this would be something like `realm.objects(Foo.self).filter("query").limit(100).subscribe("Foo query", overwrite: true)`.

An alternative API could be to update it on the subscription itself (which might be a bit more discoverable):

```swift
let newquery = realm.objects(Foo.self).filter("query").limit(100)
subscription.update(newquery)
```

which would also open for the even more concise (since the subscription is already typed):

```swift
subscription.update("query")
```

**Comment by tgoyne** [comment]
I do not think that moving away from an immutable builder API for queries is a good idea.

**Comment by astigsen** [comment]
I agree that we probably don't want to move away from our builder API for queries, but that does not mean that we could not add some convenience methods to make it more discoverable.

It might also be worth considering if we could bind the UI (our listeners) directly to the subscription, rather than the query itself, so that updating the query in the subscription is also reflected in the UI.

**Comment by cmelchior** [comment]
Being able to update the query held by a `Results` class is also something other users are requesting as the use case isn't only restricted to Subscriptions. See e.g. the Java issue here: https://github.com/realm/realm-java/issues/6216
