### ISSUE TITLE
Upgrade to Realm Sync v4.x w Client Resync

### ISSUE THREAD

**Issue by kneth** [realm/realm-object-store#776]
Realm Sync v4.0.0 has a number of breaking changes, and we need to incorporate them into object store before the SDKs can be upgraded.

* New error codes
* Client resync

**Comment by tgoyne** [comment]
The new async open functionality doesn't appear to require any SDK API changes.

For client reset, I think the only thing we need API-wise in the SDKs is a new sync config option that looks something like:

```
enum ClientResetMode {
    // Transparent automatic client reset, reapplying all changes which were
    // never sent to the server on top of the redownloaded realm
    case automaticallyRecoverLocalChanges
    // Transparent automatic client reset, discarding all local changes which
    // were never sent to the server
    case automaticallyDiscardLocalChanges
    // Do the existing old client reset thing (save a backup copy, tell the user to figure it out)
    case manual
}

struct SyncConfig {
    ...
    var clientResetMode: ClientResetMode = .automaticallyRecoverLocalChanges
}
```

If either of the automatic options are selected we'd handle client resets entirely within the objectstore code without needing any SDK or end-user code.

The other customizable option that sync exposes is the temporary directory used. I think we can just put that in a subdirectory of our existing metadata directory rather than exposing it as a separate parameter, but maybe we need to make it customizable?

**Comment by roberhofer** [comment]
Enabled by default?

**Comment by tgoyne** [comment]
Yes, unless there's some major gotchas it should almost certainly be enabled by default.

**Comment by cmelchior** [comment]
It looks fine to me. In case of `manual` I assume we would continue to report the Client Reset through the Sync error handler like today?

Bikeshedding the names, they feel a bit long to me. I would probably go with:
```
RecoverLocalChanges  // We need to fully understand the behaviour of this, otherwise it seems pointless to have the other options
DisregardLocalChanges
Manual
```

**Comment by nirinchev** [comment]
If I'm being honest, it feels a bit lazy asking the user to choose between all the different modes. E.g. I imagine for someone to properly handle the manual mode, they'd need to implement a poor man's version of @morten-krogh's work and is unlikely that anyone will ever want that. Then telling people to choose between discarding or recovering changes without more details is fairly misleading - I don't imagine anyone would say "sure, just throw my data away", so they would always choose the recover option because the subtleties around it are going to be extremely challenging to explain and understand by the average user. So I would argue that unless we can find a very compelling real-world use case for the manual and discarding option, we should just go with a single API that recovers the local changes.

**Comment by kneth** [comment]
I can easily imagine that having the possibility to choose how to react to a client reset is good idea. For example, a client reset in the data adapters might require some work by the operator. So the manual mode could be used to stop the data adapter and ask the operator for help.

**Comment by nirinchev** [comment]
How would the operator help though? While I haven't been involved with the data adapters, it seems like this is more theoretical than practical - if we do encounter a client reset, are we going to give the user two almost identical 50gb realm files and tell him to open them in studio and copy what they feel like from the old to the new one? I would be pretty upset if I was the operator for that system 😅 Or do we have some better tooling for the adapters that would make that more manageable?

**Comment by kneth** [comment]
The operator might have to clean the state and rerun the loader.

**Comment by tgoyne** [comment]
I'm not sure how exposing the option is "lazy"; it'd be strictly less work to just not expose it.

Realistically 99.9% of users are never going to touch the default and maybe there's no point with exposing the choice. I'm just not confident that there really is no case where users would want to turn it off.

**Comment by roberhofer** [comment]
If these options are only relevant on the Adapter side, perhaps we can expose these options as configuration parameters on the server/adapter side - and not expose for SDK's used for client development (e.g. Android, iOS)?

**Comment by nirinchev** [comment]
It's"lazy" in the sense that we're taking the easy way out rather than thinking hard and coming up with a streamlined API.

**Comment by tgoyne** [comment]
I don't really understand. Enabling automatic client reset by default with an option to turn it off and enabling it by default without an option to turn it off require basically the same level of confidence that it works correctly for the overwhelming majority of use-cases.

**Comment by kneth** [comment]
I can't see it is "lazy" to choose a default covering almost all use case but expose other options for the remaining use cases. Actually, identifying the best default is a hard problem since it's not a technical problem :smile:.

@roberhofer As the data adapters are "just" JS applications using the JS SDK, I think we need expose more than one option in the JS SDK.

**Comment by bmunkholm** [comment]
@kneth Was this resolved?

**Comment by kneth** [comment]
@bmunkholm This issue has been resolve in two PRs:

* Error codes: #805 
* Client resync: #778
